[package]
name = "typst-unigoe"
version = "0.3.0"
entrypoint = "main.typ"
authors = [
  "Lorenz Glißmann <lorenz.glissmann@uni-goettingen.de>",
  "Julius Hunold <julius.hunold@stud.uni-goettingen.de>"
]
license = "MIT"
description = "A highly dynamic and customizable unofficial thesis template for Georg-August-Universität Göttingen, supporting multiple faculties. Forked from Lorenz Glißmann's CS/DS template."
repository = "https://github.com/dfgsteam/typst-unigoe"
exclude = ["content"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"